### ISSUE TITLE
Make a presentation of the game

### ISSUE THREAD

**Issue by MrKekMan04** [MrKekMan04/English-With-Lancelot#20]
In the presentation, show the main idea of the game.

В презентации показать основную идею игры.

**Comment by 61X-at** [comment]
[Eng with Lanc.pptx](https://github.com/MrKekMan04/English-With-Lancelot/files/11311476/Eng.with.Lanc.pptx)


[Речь для ПП.docx](https://github.com/MrKekMan04/English-With-Lancelot/files/11303592/default.docx)
