### ISSUE TITLE
Draw sprites and backgrounds for a plot

### ISSUE THREAD

**Issue by MrKekMan04** [MrKekMan04/English-With-Lancelot#21]
Draw sprites and backgrounds for a plot.

Нарисовать спрайты и фоны для сюжета.
2 бэкграунда: Кузня и Гильдия. Главный герой, Кузнец, Секретарь гильдии, Меч в камне.

**Comment by MrKekMan04** [comment]
Backgrounds
[КузняBG.zip](https://github.com/MrKekMan04/English-With-Lancelot/files/11356030/BG.zip)

**Comment by wheru** [comment]
[MechVKamne.zip](https://github.com/MrKekMan04/English-With-Lancelot/files/11357289/MechVKamne.zip)

**Comment by wheru** [comment]
[персонажи.zip](https://github.com/MrKekMan04/English-With-Lancelot/files/11415778/default.zip)
