### ISSUE TITLE
Draw sprites for mini-games

### ISSUE THREAD

**Issue by MrKekMan04** [MrKekMan04/English-With-Lancelot#26]
Draw backgrounds for each mini-game, UI. Finish the character animation.

Нарисовать фоны для каждой мини-игры, UI. Дорисовать анимацию персонажа.

**Comment by wheru** [comment]
[mini games.zip](https://github.com/MrKekMan04/English-With-Lancelot/files/11523222/mini.games.zip)

**Comment by wheru** [comment]
[mini games.zip](https://github.com/MrKekMan04/English-With-Lancelot/files/11554223/mini.games.zip)

**Comment by wheru** [comment]
[рыцарь.zip](https://github.com/MrKekMan04/English-With-Lancelot/files/11554236/default.zip)
